//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.BusRoutes = new HashSet<BusRoute>();
        }
    
        public int Id { get; set; }
        [DisplayName("Bus Service")]
        public int BusServiceId { get; set; }
        [DisplayName("Bus Number")]
        public string BusNumber { get; set; }
        public int Seats { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public HttpPostedFileBase UpdateImage { get; set; }
        [DisplayName("Fare")]
        public Nullable<decimal> Price { get; set; }
    
        public virtual BusService BusService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusRoute> BusRoutes { get; set; }
    }
}
