//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BusRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusRoute()
        {
            this.UserTickets = new HashSet<UserTicket>();
        }
    
        public int Id { get; set; }
        [DisplayName("Bus")]
        public int BusId { get; set; }
        [DisplayName("Route")]
        public int RouteId { get; set; }
        [DisplayName("Arrival Time")]
        public System.DateTime ArrivalTime { get; set; }
        [DisplayName("Departure Time")]
        public System.DateTime DepartureTime { get; set; }
        [DisplayName("Reserve Seats")]
        public int ReservedSeats { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Route Route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTicket> UserTickets { get; set; }
    }
}
