//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class UserTicket
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        [DisplayName("Reserved Seats")]
        public int ReservedSeats { get; set; }
        [DisplayName("Ticket Code")]
        public string TicketId { get; set; }
        public int BusRouteId { get; set; }
        [DisplayName("Total Fare")]
        public Nullable<decimal> PaidFare { get; set; }
    
        public virtual BusRoute BusRoute { get; set; }
        public virtual User User { get; set; }
    }
}
